name: Backend associated test file check
on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  run_tests:
    name: Run backend associated test file checks
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      - uses: ./.github/actions/merge
      - name: Cache third party dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-third-party-dependencies
        with:
          path: |
            /home/runner/work/oppia/oppia/third_party
            /home/runner/work/oppia/oppia/node_modules
            /home/runner/work/oppia/yarn_cache
            /home/runner/work/oppia/oppia_tools/buf-*
            /home/runner/work/oppia/oppia_tools/elasticsearch-*
            /home/runner/work/oppia/oppia_tools/node-*
            /home/runner/work/oppia/oppia_tools/redis-cli-*
            /home/runner/work/oppia/oppia_tools/yarn-*
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock', 'dependencies.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run backend associated test file check
        run: PYTHONIOENCODING=utf-8 python -m scripts.check_backend_associated_test_file
      - name: Report failure if failed on oppia/oppia develop branch
        if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop'}}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "Some backend files lack an associated test file."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
